# Generated by Django 4.1.3 on 2022-11-30 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_control', '0002_message_messageattachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='messageattachment',
            options={'ordering': ('created_at',)},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='messageattachment',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
