# Generated by Django 4.1.3 on 2023-02-01 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0005_customuser_is_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_user',
        ),
    ]
