# Generated by Django 4.1.3 on 2023-02-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0011_code_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='code',
            field=models.CharField(default='JPLuXQ', max_length=100, unique=True),
        ),
    ]
