# Generated by Django 4.1.3 on 2023-02-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0015_alter_code_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='id',
        ),
        migrations.RemoveField(
            model_name='code',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='code',
            name='code',
            field=models.CharField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True),
        ),
    ]
