# Generated by Django 4.1.3 on 2023-02-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0016_remove_code_id_remove_code_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='code',
            field=models.CharField(max_length=16, primary_key=True, serialize=False, unique=True),
        ),
    ]
