# Generated by Django 4.1.3 on 2023-02-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0017_alter_code_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='code',
            name='code',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
