version: "3"

services:
  api:
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    container_name: singlechat_service_backend
    restart: unless-stopped
    volumes:
      - .:/singlechat
    ports:
      - "80:80"
    networks:
      - default
      - mysibsau
    environment:
      - SOCKET_SERVER=http://91.216.164.35:2086
  redis:
    restart: always
    image: redis:6.2
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data



networks:
  mysibsau:
    external: true

volumes:
  redisdata: