version: "3"

services:
  api:
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    container_name: singlechat_service_backend
    restart: unless-stopped
    volumes:
      - .:/singlechat
    ports:
      - "8000:8000"
    networks:
      - default
      - mysibsau
    environment:
      - SOCKET_SERVER=http://91.216.164.35:2086
      - MESSENGERS_SERVER=http://91.216.164.35:5000
      - MYSQL_ENGINE=django.db.backends.mysql
      - MYSQL_DB=django_db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin4321
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
    depends_on:
      - db
  db:
    image: mysql
    container_name: singlechat_service_database
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin4321
      - MYSQL_DATABASE=django_db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin4321
    ports:
      - "3306:3306"

volumes:
  mysql_data:

networks:
  mysibsau:
    external: true